package part02;

import java.util.ArrayList;

/**
 * This class will be generated by an ImageManager as a result of a search and
 * is responsible for managing a collection of ImageRecord objects.
 */
public class ImageAlbum {

	private ArrayList<ImageRecord> album = new ArrayList<ImageRecord>(); // ArrayList used to hold collections of ImageRecords
	private int count = -1; // counter used to keep track of the index that has been accessed in each album

	/**
	 * Constructor for ImageAlbum class.
	 * 
	 * @param album - a collection of ImageRecord objects.
	 */
	public ImageAlbum(ArrayList<ImageRecord> album) {
		this.album = album;
		sortByDate(this.album); // sorts album into chronological order

	}

	/**
	 * Sorts the provided ArrayList of ImageRecord objects by date in chronological
	 * order. Uses the bubble sort algorithm to sort dates.
	 * 
	 * @param album - the collection of ImageRecords to be sorted.
	 */
	public void sortByDate(ArrayList<ImageRecord> album) {
		ImageRecord temp;
		int swaps; // Counts number of swaps made by algorithm
		// Perform bubble sort until no swaps are made
		do {
			swaps = 0;
			for (int i = 0; i < album.size() - 1; i++) {
				// Compare dates of consecutive ImageRecord objects
				if (album.get(i).getDateTaken().isAfter(album.get(i + 1).getDateTaken())) {
					// Swap if the current date is after the next date
					temp = album.get(i);
					album.set(i, album.get(i + 1));
					album.set(i + 1, temp);
					swaps++;
				}
			}
		} while (swaps > 0);
	}

	/**
	 * Retrieves the first ImageRecord object from the album, if the album is not
	 * empty.
	 * 
	 * @return The first ImageRecord object in the album or null if the album is
	 *         empty.
	 */
	public ImageRecord getFirst() {
		if (this.album != null) {
			count = 0;
			return this.album.get(0);
		}
		return null;

	}

	/**
	 * Retrieves the next ImageRecord object from the album, if the album is not
	 * empty, has been previously accessed and there are more ImageRecords left to
	 * retrieve.
	 * 
	 * @return The next ImageRecord object in the album, or null if the album is
	 *         empty, has not been previously accessed, or there are no more
	 *         ImageRecords to retrieve.
	 */
	public ImageRecord getNext() {
		if (this.album != null && count >= 0 && count < this.album.size() - 1) {
			return this.album.get(++count);
		}
		return null;
	}

	/**
	 * Retrieves the previous ImageRecord object from the album, if the album is not
	 * empty and there are previous ImageRecords to retrieve.
	 * 
	 * @return The previous ImageRecord object in the album, or null if the album is
	 *         empty or there are no previous ImageRecords to retrieve.
	 */
	public ImageRecord getPrevious() {
		if (this.album != null && count > 0) {
			return this.album.get(--count);
		}
		return null;
	}
}
